### ISSUE TITLE
`currentColor` should probably be `false` by default

### ISSUE THREAD

**Issue by nicooprat** [g-makarov/vite-plugin-svg-spritemap#10]
Hi there,

Thanks for your work. We just spent a lot of times figuring out why our icons were missing their color, until we found out that `currentColor` option is `true` by default. It seems way too opinionated IMO. What about setting it `false` by default? Might save some time to others.

Regards

**Comment by g-makarov** [comment]
Hi, it does make sense. I absolutely agree that it can be unclear and confusing for users who have just started working with the plugin. I'll update the library with a major version so users who are already using the plugin won't be affected. This issue will be resolved after version 1.0.0 is released
