### ISSUE TITLE
Generating more than one result sprites

### ISSUE THREAD

**Issue by kdubrovsky** [g-makarov/vite-plugin-svg-spritemap#2]
For example:
I have 2-3 folders with icons that should be assembled into sprites. Now all icons from all folders are collected into one final file. But it would be convenient either to keep the structure of the source folders, or to add a prefix with the folder name to the sprites.

**Comment by g-makarov** [comment]
@kdubrovsky hi, actually you can use plugin twice for different paths

For example:
```ts
export default defineConfig({
  plugins: [
    svgSpritemap({
      pattern: 'src/assets/icons/*.svg',
      filename: 'icons/spritemap.svg',
    }),
    svgSpritemap({
      pattern: 'src/assets/icons/raw/*.svg',
      filename: 'icons/raw-spritemap.svg',
    }),
  ]
})
```

Let me know if it doesn't work for you

**Comment by kdubrovsky** [comment]
Thanks a lot! It fits all requirements and nicely configurable.
