### ISSUE TITLE
How to use in laravel bootstrap website?

### ISSUE THREAD

**Issue by mvdgeijn** [g-makarov/vite-plugin-svg-spritemap#6]
Just wondering how to use this in a Laravel bootstrap website. Trying to call @vite('assets/icons.svg#mail'  ), but to no effect. The icons.svg file is found on the dev server, but no icon is shown. I think the #mail is ignored or has to be used in another way?

**Comment by g-makarov** [comment]
Hi, sorry for the delay. Is this still an issue?
